# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mr_FH7RyUAZrsomdHyv4XCm6YRBP5Xy4
"""

a=8
b=6
p=9

if (a+p)<(b+p):
  print("Elevador B")
elif (a+p)>(b+p):
  print("Elevador A")
elif (a+p)==(b+p):
  print("Elevador A")

cUnidades=int(input("¿Cuanto ha gastado?: "))
impuesto=0
if cUnidades<=100:
  impuesto=0
  print("No se le ha aplicado ningun impuesto")
elif cUnidades>100 and cUnidades<=200:
  impuesto = cUnidades*0.5
  print("Impuesto aplicado: $", impuesto)
elif cUnidades>200:
  impuesto=cUnidades*0.7
  print("Impuesto aplicado: $", impuesto)

contraseña = input("Introduzca la contraseña: ")
cDigit=False
cUpper=False
for i in contraseña:
  if i.isdigit():
    cDigit=True
  elif i.isupper():
    cUpper=True
if cDigit==True and cUpper==True and len(contraseña)>=8:
  print("Contraseña segura")
else:
  print("Contraseña no segura")